# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      couchbase-dependencies:
        patterns:
          - 'com.couchbase.client:*'
      grpc-dependencies:
        patterns:
          - 'io.grpc:*'
          - 'com.google.protobuf:*'
          - 'com.google.api.grpc:*'
          - 'io.github.lognet:grpc*'
          - 'com.salesforce.servicelibs:reactor-grpc*'
          - 'org.xolstice.maven.plugins:protobuf-maven-plugin'
        update-types:
          - "minor"
          - "patch"
      narayana-dependencies:
        patterns:
          - 'io.agroal:*'
          - 'dev.snowdrop:narayana*'
